---
engines:
  phpmd:
    enabled: true
    config:
      file_extensions: "php,inc,module,install"
  phpcodesniffer:
    enabled: true
    config:
      standard: "Drupal"
      ignore_warnings: true